name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  ubuntu_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make re
    - name: make std
      run: make re STD=1

  macos_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make re
    - name: make std
      run: make re STD=1e
